name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.1.0
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  realm: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  realm_generator: ^1.7.0
dependency_overrides:
  analyzer: ^5.12.0
flutter:
  uses-material-design: true
